#!/bin/sh

repo_name=$1
test -z $repo_name && echo "Repo name required." 1>&2 && exit 1

curl -u 'fengcs' https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"}"
git remote add origin git@github.com:fengcs/${repo_name}.git
git push -u origin master
